Project 3 Load Balancer: LoadBalancer Class Reference
LoadBalancer Class Reference
Manages request queues and a pool of web servers.
#include <LoadBalancer.h>
Public Member Functions
LoadBalancer (int initialServers, const std::string &balancerLabel="LoadBalancer")
Constructs a new load balancer.
int getServerCount () const
Gets the number of servers in the pool.
std::size_t getQueueSize () const
Gets the number of requests in the queue.
std::vector< Request > getQueueSnapshot (std::size_t maxItems) const
Gets a non-destructive snapshot of queued requests.
std::vector< ServerSnapshot > getServerSnapshots () const
Gets a snapshot of every server and its current state.
int getActiveServerCount () const
Gets the number of currently active (busy) servers.
int getIdleServerCount () const
Gets the number of currently inactive (idle) servers.
void enqueueRequest (const Request &request)
Enqueues a new request.
bool hasPendingRequests () const
Checks whether work remains in queue or servers.
bool dispatchToServers (Logger &logger)
Dispatches queued requests and advances active work.
void tick ()
Advances the internal clock by one cycle.
void addServer ()
Adds one server to the pool.
void removeServer ()
Removes one idle server from the pool if possible.
int getClock () const
Gets the current clock cycle.
void evaluateScaling (int minQueuePerServer, int maxQueuePerServer, Logger &logger)
Evaluates scaling thresholds and adjusts capacity.
int getTotalRequestsCount () const
Gets the total accepted requests count.
int getTotalRequestsHandledCount () const
Gets the total completed requests count.
int getTotalRequestsRemainingCount () const
Gets the total requests not yet completed.
int getTotalServersAddedCount () const
Gets the total number of servers added by scaling.
int getTotalServersRemovedCount () const
Gets the total number of servers removed by scaling.
Private Member Functions
std::string formatServerTag (const WebServer &server) const
Formats a labeled server tag for logs.
bool removeOneIdleServer (Logger &logger)
Removes one idle server if available.
void processDeferredScaleDown (Logger &logger)
Processes deferred scale-down operations.
Private Attributes
std::queue< Request > requestQueue_
FIFO queue of pending requests.
std::vector< WebServer > servers_
Pool of simulated servers.
int clock_
Current simulation clock.
int nextServerId_
Identifier to assign to the next created server.
int totalRequests_
Total accepted/enqueued requests.
int totalRequestsHandled_
Total completed requests.
int pendingScaleDown_
Requested scale-down removals waiting for idle capacity.
int totalServersAdded_
Total servers added via scaling.
int totalServersRemoved_
Total servers removed via scaling.
std::string balancerLabel_
Label used in log output to identify this balancer.
Detailed Description
Manages request queues and a pool of web servers.
Definition at line 31 of file LoadBalancer.h.
Constructor & Destructor Documentation
LoadBalancer()
LoadBalancer::LoadBalancer (int initialServers, const std::string & balancerLabel = "LoadBalancer") explicit
Constructs a new load balancer.
Constructs a load balancer with an initial server pool.
Parameters
initialServers Number of servers to start with.
balancerLabel Human-readable label for logs.
initialServers Number of servers to create initially.
balancerLabel Human-readable balancer label used in logs.
Definition at line 16 of file LoadBalancer.cpp.
References balancerLabel_, clock_, nextServerId_, pendingScaleDown_, requestQueue_, servers_, totalRequests_, totalRequestsHandled_, totalServersAdded_, and totalServersRemoved_.
Member Function Documentation
addServer()
void LoadBalancer::addServer ()
Adds one server to the pool.
Adds one new server to the pool.
Definition at line 189 of file LoadBalancer.cpp.
References nextServerId_, and servers_.
Referenced by evaluateScaling().
dispatchToServers()
bool LoadBalancer::dispatchToServers (Logger & logger)
Dispatches queued requests and advances active work.
Dispatches queued work and advances active server requests.
Parameters
logger Logger to record handled requests.
Returns
True if any request was dispatched, false otherwise.
Parameters
logger Logger used for dispatch/progress/completion messages.
Returns
True when at least one queued request was assigned this cycle.
Definition at line 136 of file LoadBalancer.cpp.
References clock_, formatServerTag(), Request::ipIn, Request::ipOut, Logger::log(), processDeferredScaleDown(), requestQueue_, servers_, and totalRequestsHandled_.
Referenced by main().
enqueueRequest()
void LoadBalancer::enqueueRequest (const Request & request)
Enqueues a new request.
Adds a request to the queue and increments totals.
Parameters
request Request to add.
request Request to enqueue.
Definition at line 109 of file LoadBalancer.cpp.
References requestQueue_, and totalRequests_.
evaluateScaling()
void LoadBalancer::evaluateScaling (int minQueuePerServer, int maxQueuePerServer, Logger & logger)
Evaluates scaling thresholds and adjusts capacity.
Applies auto-scaling rules based on queue-per-server ratio.
Parameters
minQueuePerServer Minimum queue-per-server threshold.
maxQueuePerServer Maximum queue-per-server threshold.
logger Logger for scaling events.
minQueuePerServer Threshold below which scale-down is considered.
maxQueuePerServer Threshold above which scale-up is triggered.
logger Logger used for scaling event messages.
Definition at line 219 of file LoadBalancer.cpp.
References addServer(), balancerLabel_, clock_, Logger::log(), pendingScaleDown_, removeOneIdleServer(), requestQueue_, servers_, and totalServersAdded_.
Referenced by main().
formatServerTag()
std::string LoadBalancer::formatServerTag (const WebServer & server) const private
Formats a labeled server tag for logs.
Formats a server tag for consistent logging output.
Parameters
server Server whose tag should be generated.
Returns
Formatted server label.
Parameters
server Server to describe.
Returns
String tag with balancer label and server id.
Definition at line 353 of file LoadBalancer.cpp.
References balancerLabel_, and WebServer::getId().
Referenced by dispatchToServers().
getActiveServerCount()
int LoadBalancer::getActiveServerCount () const
Gets the number of currently active (busy) servers.
Gets number of busy servers.
Returns
Active server count.
Count of active servers.
Definition at line 87 of file LoadBalancer.cpp.
References servers_.
Referenced by getIdleServerCount(), and logSimulationEndSummary().
getClock()
int LoadBalancer::getClock () const
Gets the current clock cycle.
Gets the current clock value.
Returns
Clock cycle count.
Simulation clock.
Definition at line 209 of file LoadBalancer.cpp.
References clock_.
Referenced by main().
getIdleServerCount()
int LoadBalancer::getIdleServerCount () const
Gets the number of currently inactive (idle) servers.
Gets number of idle servers.
Returns
Idle server count.
Count of inactive servers.
Definition at line 101 of file LoadBalancer.cpp.
References getActiveServerCount(), and servers_.
Referenced by logSimulationEndSummary().
getQueueSize()
std::size_t LoadBalancer::getQueueSize () const
Gets the number of requests in the queue.
Gets the number of queued requests.
Returns
Queue size.
Current queue length.
Definition at line 43 of file LoadBalancer.cpp.
References requestQueue_.
Referenced by initializeMetrics(), logSimulationEndSummary(), logSimulationStartSnapshot(), and updateMetrics().
getQueueSnapshot()
std::vector< Request > LoadBalancer::getQueueSnapshot (std::size_t maxItems) const
Gets a non-destructive snapshot of queued requests.
Gets a copy of the first queued requests.
Parameters
maxItems Maximum number of queued requests to include.
Returns
Requests from the front of the queue.
Parameters
maxItems Maximum number of requests to include.
Returns
Snapshot vector of queued requests.
Definition at line 52 of file LoadBalancer.cpp.
References requestQueue_.
getServerCount()
int LoadBalancer::getServerCount () const
Gets the number of servers in the pool.
Returns
Server count.
Definition at line 35 of file LoadBalancer.cpp.
References servers_.
Referenced by initializeMetrics(), logSimulationEndSummary(), main(), and updateMetrics().
getServerSnapshots()
std::vector< ServerSnapshot > LoadBalancer::getServerSnapshots () const
Gets a snapshot of every server and its current state.
Gets the current snapshot of all servers.
Returns
Vector of server snapshots.
Vector with one snapshot entry per server.
Definition at line 70 of file LoadBalancer.cpp.
References ServerSnapshot::busy, ServerSnapshot::id, ServerSnapshot::request, and servers_.
getTotalRequestsCount()
int LoadBalancer::getTotalRequestsCount () const
Gets the total accepted requests count.
Gets total accepted request count.
Returns
Total requests.
Number of accepted requests.
Definition at line 312 of file LoadBalancer.cpp.
References totalRequests_.
Referenced by logSimulationEndSummary(), and main().
getTotalRequestsHandledCount()
int LoadBalancer::getTotalRequestsHandledCount () const
Gets the total completed requests count.
Gets total completed request count.
Returns
Total requests handled.
Number of handled requests.
Definition at line 320 of file LoadBalancer.cpp.
References totalRequestsHandled_.
Referenced by logSimulationEndSummary(), and main().
getTotalRequestsRemainingCount()
int LoadBalancer::getTotalRequestsRemainingCount () const
Gets the total requests not yet completed.
Gets total number of requests remaining.
Returns
Total requests remaining.
Definition at line 328 of file LoadBalancer.cpp.
References totalRequests_, and totalRequestsHandled_.
Referenced by logSimulationEndSummary(), and main().
getTotalServersAddedCount()
int LoadBalancer::getTotalServersAddedCount () const
Gets the total number of servers added by scaling.
Gets total number of servers added by scaling.
Returns
Servers added.
Number of added servers.
Definition at line 336 of file LoadBalancer.cpp.
References totalServersAdded_.
Referenced by logSimulationEndSummary().
getTotalServersRemovedCount()
int LoadBalancer::getTotalServersRemovedCount () const
Gets the total number of servers removed by scaling.
Gets total number of servers removed by scaling.
Returns
Servers removed.
Number of removed servers.
Definition at line 344 of file LoadBalancer.cpp.
References totalServersRemoved_.
Referenced by logSimulationEndSummary().
hasPendingRequests()
bool LoadBalancer::hasPendingRequests () const
Checks whether work remains in queue or servers.
Checks whether any work remains to be processed.
Returns
True if queue has items, false otherwise.
True when queue is non-empty or a server is busy.
Definition at line 118 of file LoadBalancer.cpp.
References requestQueue_, and servers_.
processDeferredScaleDown()
void LoadBalancer::processDeferredScaleDown (Logger & logger) private
Processes deferred scale-down operations.
Processes pending scale-down requests once servers become idle.
Parameters
logger Logger for deferred removal events.
logger Logger for scale-down events.
Definition at line 299 of file LoadBalancer.cpp.
References pendingScaleDown_, and removeOneIdleServer().
Referenced by dispatchToServers().
removeOneIdleServer()
bool LoadBalancer::removeOneIdleServer (Logger & logger) private
Removes one idle server if available.
Parameters
logger Logger for removal events.
Returns
True if a server was removed.
Parameters
logger Logger for removal events.
Returns
True if a server was removed, false otherwise.
Definition at line 277 of file LoadBalancer.cpp.
References balancerLabel_, clock_, Logger::log(), servers_, and totalServersRemoved_.
Referenced by evaluateScaling(), and processDeferredScaleDown().
removeServer()
void LoadBalancer::removeServer ()
Removes one idle server from the pool if possible.
Removes one idle server, preferring most recently added.
Definition at line 196 of file LoadBalancer.cpp.
References servers_.
tick()
void LoadBalancer::tick ()
Advances the internal clock by one cycle.
Advances the balancer clock by one cycle.
Definition at line 182 of file LoadBalancer.cpp.
References clock_.
Referenced by main().
Member Data Documentation
balancerLabel_
std::string LoadBalancer::balancerLabel_ private
Label used in log output to identify this balancer.
Definition at line 195 of file LoadBalancer.h.
Referenced by evaluateScaling(), formatServerTag(), LoadBalancer(), and removeOneIdleServer().
clock_
int LoadBalancer::clock_ private
Current simulation clock.
Definition at line 181 of file LoadBalancer.h.
Referenced by dispatchToServers(), evaluateScaling(), getClock(), LoadBalancer(), removeOneIdleServer(), and tick().
nextServerId_
int LoadBalancer::nextServerId_ private
Identifier to assign to the next created server.
Definition at line 183 of file LoadBalancer.h.
Referenced by addServer(), and LoadBalancer().
pendingScaleDown_
int LoadBalancer::pendingScaleDown_ private
Requested scale-down removals waiting for idle capacity.
Definition at line 189 of file LoadBalancer.h.
Referenced by evaluateScaling(), LoadBalancer(), and processDeferredScaleDown().
requestQueue_
std::queue<Request> LoadBalancer::requestQueue_ private
FIFO queue of pending requests.
Definition at line 177 of file LoadBalancer.h.
Referenced by dispatchToServers(), enqueueRequest(), evaluateScaling(), getQueueSize(), getQueueSnapshot(), hasPendingRequests(), and LoadBalancer().
servers_
std::vector<WebServer> LoadBalancer::servers_ private
Pool of simulated servers.
Definition at line 179 of file LoadBalancer.h.
Referenced by addServer(), dispatchToServers(), evaluateScaling(), getActiveServerCount(), getIdleServerCount(), getServerCount(), getServerSnapshots(), hasPendingRequests(), LoadBalancer(), removeOneIdleServer(), and removeServer().
totalRequests_
int LoadBalancer::totalRequests_ private
Total accepted/enqueued requests.
Definition at line 185 of file LoadBalancer.h.
Referenced by enqueueRequest(), getTotalRequestsCount(), getTotalRequestsRemainingCount(), and LoadBalancer().
totalRequestsHandled_
int LoadBalancer::totalRequestsHandled_ private
Total completed requests.
Definition at line 187 of file LoadBalancer.h.
Referenced by dispatchToServers(), getTotalRequestsHandledCount(), getTotalRequestsRemainingCount(), and LoadBalancer().
totalServersAdded_
int LoadBalancer::totalServersAdded_ private
Total servers added via scaling.
Definition at line 191 of file LoadBalancer.h.
Referenced by evaluateScaling(), getTotalServersAddedCount(), and LoadBalancer().
totalServersRemoved_
int LoadBalancer::totalServersRemoved_ private
Total servers removed via scaling.
Definition at line 193 of file LoadBalancer.h.
Referenced by getTotalServersRemovedCount(), LoadBalancer(), and removeOneIdleServer().
The documentation for this class was generated from the following files:
LoadBalancer.h
LoadBalancer.cpp