Project 3 Load Balancer: IpBlocker Class Reference
IpBlocker Class Reference
IPv4 allowlist blocker that rejects out-of-range sources.
#include <IpBlocker.h>
Public Member Functions
bool addAllowedRange (const IpRange &range)
Adds an allowed IPv4 range.
bool isAllowed (const std::string &ip) const
Checks whether an IPv4 address is within allowed ranges.
Private Attributes
std::vector< std::pair< std::uint32_t, std::uint32_t > > allowedRanges_
Stored allowed IPv4 ranges in 32-bit numeric form.
Detailed Description
IPv4 allowlist blocker that rejects out-of-range sources.
Definition at line 25 of file IpBlocker.h.
Member Function Documentation
addAllowedRange()
bool IpBlocker::addAllowedRange (const IpRange & range)
Adds an allowed IPv4 range.
Adds an allowed IPv4 range to the blocker.
Parameters
range The range to allow.
Returns
True if range is valid and added, false otherwise.
Parameters
range Inclusive string range to add.
Returns
True when both addresses parse successfully.
Definition at line 47 of file IpBlocker.cpp.
References allowedRanges_, IpRange::end, and IpRange::start.
Referenced by main().
isAllowed()
bool IpBlocker::isAllowed (const std::string & ip) const
Checks whether an IPv4 address is within allowed ranges.
Checks whether an IPv4 address is allowed.
Parameters
ip IP address string.
Returns
True if allowed, false otherwise.
Parameters
ip Source IPv4 string.
Returns
True when the address falls in any configured range.
Definition at line 67 of file IpBlocker.cpp.
References allowedRanges_.
Referenced by main(), makeBiasedRequest(), and simulateIncomingRequests().
Member Data Documentation
allowedRanges_
std::vector<std::pair<std::uint32_t, std::uint32_t> > IpBlocker::allowedRanges_ private
Stored allowed IPv4 ranges in 32-bit numeric form.
Definition at line 43 of file IpBlocker.h.
Referenced by addAllowedRange(), and isAllowed().
The documentation for this class was generated from the following files:
IpBlocker.h
IpBlocker.cpp