Project 3 Load Balancer: Logger Class Reference
Logger Class Reference
Handles logging events and summaries.
#include <Logger.h>
Public Member Functions
Logger (const std::string &filePath)
Constructs a logger that appends to a file.
void log (const std::string &message)
Logs a single line message.
Private Attributes
std::ofstream file_
Output file stream for append-only logging.
Detailed Description
Handles logging events and summaries.
Definition at line 14 of file Logger.h.
Constructor & Destructor Documentation
Logger()
Logger::Logger (const std::string & filePath) explicit
Constructs a logger that appends to a file.
Parameters
filePath Log file path.
filePath Path to log file.
Definition at line 12 of file Logger.cpp.
References file_.
Member Function Documentation
log()
void Logger::log (const std::string & message)
Logs a single line message.
Writes one line to the configured log file.
Parameters
message Text to log.
message Message text to append.
Definition at line 18 of file Logger.cpp.
References file_.
Referenced by LoadBalancer::dispatchToServers(), LoadBalancer::evaluateScaling(), logSimulationEndSummary(), logSimulationStartSnapshot(), main(), LoadBalancer::removeOneIdleServer(), and simulateIncomingRequests().
Member Data Documentation
file_
std::ofstream Logger::file_ private
Output file stream for append-only logging.
Definition at line 30 of file Logger.h.
Referenced by log(), and Logger().
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp