Project 3 Load Balancer: main.cpp File Reference
main.cpp File Reference
Entry point and simulation orchestration.
#include "Config.h"
#include "IpBlocker.h"
#include "LoadBalancer.h"
#include "Logger.h"
#include "MetricsReporter.h"
#include "Request.h"
#include "Switch.h"
#include <iostream>
#include <random>
#include <string>
Classes
struct IncomingTrafficResult
Tracks accepted/rejected incoming request counts per job type.
Functions
static Request makeBiasedRequest (const IpBlocker &ipBlocker, double blockedTrafficRate)
Generates a request biased toward blocked or allowed traffic.
static IncomingTrafficResult simulateIncomingRequests (Switch &switchRouter, const IpBlocker &ipBlocker, double blockedTrafficRate, int currentClock, Logger &logger)
Simulates one cycle of incoming traffic generation and routing.
int main ()
Runs the full load-balancing simulation.
Detailed Description
Entry point and simulation orchestration.
Definition in file main.cpp.
Function Documentation
main()
int main ()
Runs the full load-balancing simulation.
Returns
Exit code (0 on success).
Definition at line 141 of file main.cpp.
References IncomingTrafficResult::acceptedProcessingRequests, IncomingTrafficResult::acceptedStreamingRequests, IpBlocker::addAllowedRange(), Config::allowedIpRanges, Config::blockedTrafficSimulationRate, LoadBalancer::dispatchToServers(), LoadBalancer::evaluateScaling(), LoadBalancer::getClock(), LoadBalancer::getServerCount(), LoadBalancer::getTotalRequestsCount(), LoadBalancer::getTotalRequestsHandledCount(), LoadBalancer::getTotalRequestsRemainingCount(), initializeMetrics(), Request::ipIn, IpBlocker::isAllowed(), Request::jobType, loadConfig(), Logger::log(), Config::logFilePath, logSimulationEndSummary(), logSimulationStartSnapshot(), makeBiasedRequest(), Config::maxQueuePerServer, Config::minQueuePerServer, IncomingTrafficResult::rejectedProcessingRequests, IncomingTrafficResult::rejectedStreamingRequests, Switch::routeRequest(), Config::scalingCheckInterval, simulateIncomingRequests(), Streaming, LoadBalancer::tick(), LoadBalancerMetrics::totalRejectedRequests, and updateMetrics().
makeBiasedRequest()
Request makeBiasedRequest (const IpBlocker & ipBlocker, double blockedTrafficRate) static
Generates a request biased toward blocked or allowed traffic.
Parameters
ipBlocker Configured allowlist checker.
blockedTrafficRate Target probability of generating blocked traffic.
Returns
Generated request matching target distribution when possible.
Definition at line 38 of file main.cpp.
References Request::ipIn, IpBlocker::isAllowed(), and makeRandomRequest().
Referenced by main(), and simulateIncomingRequests().
simulateIncomingRequests()
IncomingTrafficResult simulateIncomingRequests (Switch & switchRouter, const IpBlocker & ipBlocker, double blockedTrafficRate, int currentClock, Logger & logger) static
Simulates one cycle of incoming traffic generation and routing.
Parameters
switchRouter Switch used to route accepted requests.
ipBlocker Allowlist checker for source IPs.
blockedTrafficRate Target blocked-traffic ratio for generation.
currentClock Current simulation cycle for logging.
logger Logger used for traffic event output.
Returns
Accepted/rejected counts per job type for this cycle.
Definition at line 75 of file main.cpp.
References IncomingTrafficResult::acceptedProcessingRequests, IncomingTrafficResult::acceptedStreamingRequests, Request::ipIn, IpBlocker::isAllowed(), Request::jobType, Logger::log(), makeBiasedRequest(), IncomingTrafficResult::rejectedProcessingRequests, IncomingTrafficResult::rejectedStreamingRequests, Switch::routeRequest(), and Streaming.
Referenced by main().