Project 3 Load Balancer: MetricsReporter.h File Reference
MetricsReporter.h File Reference
Declares metrics aggregation and reporting helpers.
#include "LoadBalancer.h"
#include <string>
Classes
struct LoadBalancerMetrics
Aggregated metrics collected during a simulation run.
Functions
LoadBalancerMetrics initializeMetrics (const LoadBalancer &balancer)
Initializes run metrics from current load balancer state.
void updateMetrics (LoadBalancerMetrics &metrics, const LoadBalancer &balancer, int acceptedRequests, int rejectedRequests)
Updates run metrics after one cycle.
void logSimulationStartSnapshot (Logger &logger, const std::string &label, const LoadBalancer &balancer, int initialServers, int runCycles, int initialRequestCount)
Emits the start-of-run snapshot section.
void logSimulationEndSummary (Logger &logger, const std::string &label, const LoadBalancer &balancer, const LoadBalancerMetrics &metrics, int initialServers, int cyclesRun)
Emits the end-of-run summary section.
void printSimulationConsoleSummary (const LoadBalancer &processingBalancer, const LoadBalancer &streamingBalancer, int cyclesRun)
Prints a concise end-of-run summary to the console.
Detailed Description
Declares metrics aggregation and reporting helpers.
Definition in file MetricsReporter.h.
Function Documentation
initializeMetrics()
LoadBalancerMetrics initializeMetrics (const LoadBalancer & balancer)
Initializes run metrics from current load balancer state.
Parameters
balancer Current load balancer.
Returns
Initialized metrics object.
Initializes run metrics from current load balancer state.
Parameters
balancer Balancer to initialize metrics for.
Returns
Initialized metrics structure.
Definition at line 106 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::startingQueueSize, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().
logSimulationEndSummary()
void logSimulationEndSummary (Logger & logger, const std::string & label, const LoadBalancer & balancer, const LoadBalancerMetrics & metrics, int initialServers, int cyclesRun)
Emits the end-of-run summary section.
Parameters
logger Output logger.
label Workload label associated with the balancer.
balancer Current load balancer.
metrics Aggregated run metrics.
initialServers Initial server count.
cyclesRun Actual cycles completed.
Emits the end-of-run summary section.
Parameters
logger Logger used for output.
label Balancer label for log scoping.
balancer Balancer being reported.
metrics Aggregated run metrics.
initialServers Starting server count for this balancer.
cyclesRun Number of cycles completed.
Definition at line 183 of file MetricsReporter.cpp.
References LoadBalancer::getActiveServerCount(), LoadBalancer::getIdleServerCount(), LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancer::getTotalRequestsCount(), LoadBalancer::getTotalRequestsHandledCount(), LoadBalancer::getTotalRequestsRemainingCount(), LoadBalancer::getTotalServersAddedCount(), LoadBalancer::getTotalServersRemovedCount(), Logger::log(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::startingQueueSize, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().
logSimulationStartSnapshot()
void logSimulationStartSnapshot (Logger & logger, const std::string & label, const LoadBalancer & balancer, int initialServers, int runCycles, int initialRequestCount)
Emits the start-of-run snapshot section.
Parameters
logger Output logger.
label Workload label associated with the balancer.
balancer Current load balancer.
initialServers Initial server count.
runCycles Requested cycle count.
initialRequestCount Initial requests seeded before cycle 0.
Emits the start-of-run snapshot section.
Parameters
logger Logger used for output.
label Balancer label for log scoping.
balancer Balancer being reported.
initialServers Starting server count for this balancer.
runCycles Requested run length.
initialRequestCount Initial accepted request count.
Definition at line 151 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), and Logger::log().
Referenced by main().
printSimulationConsoleSummary()
void printSimulationConsoleSummary (const LoadBalancer & processingBalancer, const LoadBalancer & streamingBalancer, int cyclesRun)
Prints a concise end-of-run summary to the console.
Parameters
processingBalancer Processing load balancer.
streamingBalancer Streaming load balancer.
cyclesRun Actual cycles completed.
updateMetrics()
void updateMetrics (LoadBalancerMetrics & metrics, const LoadBalancer & balancer, int acceptedRequests, int rejectedRequests)
Updates run metrics after one cycle.
Parameters
metrics Metrics to mutate.
balancer Current load balancer.
acceptedRequests Number of accepted requests in this cycle.
rejectedRequests Number of rejected requests in this cycle.
Updates run metrics after one cycle.
Parameters
metrics Metrics object to mutate.
balancer Balancer providing state values.
acceptedRequests Accepted requests for this cycle.
rejectedRequests Rejected requests for this cycle.
Definition at line 127 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().