Project 3 Load Balancer: MetricsReporter.cpp File Reference
MetricsReporter.cpp File Reference
Implements simulation metrics aggregation and reporting.
#include "MetricsReporter.h"
#include "Logger.h"
#include "Request.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
Functions
LoadBalancerMetrics initializeMetrics (const LoadBalancer &balancer)
Initializes metrics from the balancer's starting state.
void updateMetrics (LoadBalancerMetrics &metrics, const LoadBalancer &balancer, int acceptedRequests, int rejectedRequests)
Updates metrics after one simulation cycle.
void logSimulationStartSnapshot (Logger &logger, const std::string &label, const LoadBalancer &balancer, int initialServers, int runCycles, int initialRequestCount)
Logs the start-of-run snapshot for a balancer.
void logSimulationEndSummary (Logger &logger, const std::string &label, const LoadBalancer &balancer, const LoadBalancerMetrics &metrics, int initialServers, int cyclesRun)
Logs the end-of-run summary for a balancer.
Detailed Description
Implements simulation metrics aggregation and reporting.
Definition in file MetricsReporter.cpp.
Function Documentation
initializeMetrics()
LoadBalancerMetrics initializeMetrics (const LoadBalancer & balancer)
Initializes metrics from the balancer's starting state.
Initializes run metrics from current load balancer state.
Parameters
balancer Balancer to initialize metrics for.
Returns
Initialized metrics structure.
Definition at line 106 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::startingQueueSize, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().
logSimulationEndSummary()
void logSimulationEndSummary (Logger & logger, const std::string & label, const LoadBalancer & balancer, const LoadBalancerMetrics & metrics, int initialServers, int cyclesRun)
Logs the end-of-run summary for a balancer.
Emits the end-of-run summary section.
Parameters
logger Logger used for output.
label Balancer label for log scoping.
balancer Balancer being reported.
metrics Aggregated run metrics.
initialServers Starting server count for this balancer.
cyclesRun Number of cycles completed.
Definition at line 183 of file MetricsReporter.cpp.
References LoadBalancer::getActiveServerCount(), LoadBalancer::getIdleServerCount(), LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancer::getTotalRequestsCount(), LoadBalancer::getTotalRequestsHandledCount(), LoadBalancer::getTotalRequestsRemainingCount(), LoadBalancer::getTotalServersAddedCount(), LoadBalancer::getTotalServersRemovedCount(), Logger::log(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::startingQueueSize, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().
logSimulationStartSnapshot()
void logSimulationStartSnapshot (Logger & logger, const std::string & label, const LoadBalancer & balancer, int initialServers, int runCycles, int initialRequestCount)
Logs the start-of-run snapshot for a balancer.
Emits the start-of-run snapshot section.
Parameters
logger Logger used for output.
label Balancer label for log scoping.
balancer Balancer being reported.
initialServers Starting server count for this balancer.
runCycles Requested run length.
initialRequestCount Initial accepted request count.
Definition at line 151 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), and Logger::log().
Referenced by main().
updateMetrics()
void updateMetrics (LoadBalancerMetrics & metrics, const LoadBalancer & balancer, int acceptedRequests, int rejectedRequests)
Updates metrics after one simulation cycle.
Updates run metrics after one cycle.
Parameters
metrics Metrics object to mutate.
balancer Balancer providing state values.
acceptedRequests Accepted requests for this cycle.
rejectedRequests Rejected requests for this cycle.
Definition at line 127 of file MetricsReporter.cpp.
References LoadBalancer::getQueueSize(), LoadBalancer::getServerCount(), LoadBalancerMetrics::maxServersObserved, LoadBalancerMetrics::minServersObserved, LoadBalancerMetrics::peakQueueSize, LoadBalancerMetrics::queueSamples, LoadBalancerMetrics::queueSizeAccumulator, LoadBalancerMetrics::totalIncomingRequests, and LoadBalancerMetrics::totalRejectedRequests.
Referenced by main().