Project 3 Load Balancer: Request.cpp File Reference
Request.cpp File Reference
Implements request helper utilities.
#include "Request.h"
#include <random>
#include <string>
Functions
char jobTypeToChar (JobType type)
Converts job type to a compact single-character label.
JobType jobTypeFromChar (char typeChar)
Converts a single-character label to a job type.
std::string jobTypeToString (JobType type)
Converts job type to a descriptive string.
static std::string makeRandomIp (std::mt19937 &engine)
Generates a random IPv4 address string.
Request makeRandomRequest ()
Creates a random request for simulation.
Detailed Description
Implements request helper utilities.
Definition in file Request.cpp.
Function Documentation
jobTypeFromChar()
JobType jobTypeFromChar (char typeChar)
Converts a single-character label to a job type.
Convert a single character label to JobType.
Parameters
typeChar Character representation of a job type.
Returns
Matching job type; defaults to Processing for unknown values.
Definition at line 31 of file Request.cpp.
References Processing, and Streaming.
jobTypeToChar()
char jobTypeToChar (JobType type)
Converts job type to a compact single-character label.
Convert JobType to a single character label.
Parameters
type Job type to convert.
Returns
P for processing jobs and S for streaming jobs.
Definition at line 15 of file Request.cpp.
References Processing, and Streaming.
jobTypeToString()
std::string jobTypeToString (JobType type)
Converts job type to a descriptive string.
Convert JobType to a human-readable string.
Parameters
type Job type to convert.
Returns
Human-readable job type name.
Definition at line 48 of file Request.cpp.
References Processing, and Streaming.
makeRandomIp()
std::string makeRandomIp (std::mt19937 & engine) static
Generates a random IPv4 address string.
Parameters
engine Random engine used for octet generation.
Returns
Randomly generated IPv4 address.
Definition at line 64 of file Request.cpp.
Referenced by makeRandomRequest().
makeRandomRequest()
Request makeRandomRequest ()
Creates a random request for simulation.
Create a random request for simulation.
Returns
Random request with source/destination IP, job type, and duration.
Definition at line 74 of file Request.cpp.
References Request::ipIn, Request::ipOut, Request::jobType, makeRandomIp(), Processing, Streaming, and Request::timeCycles.
Referenced by makeBiasedRequest().